"""initial_schema

Revision ID: 504b08949d85
Revises: 
Create Date: 2026-01-14 11:10:03.242944

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '504b08949d85'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sdlc_job_steps', sa.Column('tenant_id', sa.UUID(), nullable=False))
    op.drop_constraint(op.f('fk_sdlc_job_steps_job_id_sdlc_jobs'), 'sdlc_job_steps', type_='foreignkey')
    op.create_foreign_key(op.f('fk_sdlc_job_steps_job_id_sdlc_jobs'), 'sdlc_job_steps', 'sdlc_jobs', ['job_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_sdlc_job_steps_job_id_sdlc_jobs'), 'sdlc_job_steps', type_='foreignkey')
    op.create_foreign_key(op.f('fk_sdlc_job_steps_job_id_sdlc_jobs'), 'sdlc_job_steps', 'sdlc_jobs', ['job_id'], ['id'])
    op.drop_column('sdlc_job_steps', 'tenant_id')
    # ### end Alembic commands ###
